### ISSUE TITLE
Global box-sizing

### ISSUE THREAD

**Issue by albertorestifo** [bendc/frontend-guidelines#23]
Many discussions have took place about the use of global `box-sizing`.

A better practice for using `border-box` on every element is the following:

```css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

This is better because it will allow external plugins, constructed on the "standard" behaviour to use easily the standard `box-sizing`
